project:
  type: website

website:
  title: "Katherine Taylor"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/katherine-taylor
      - icon: linkedin
        href: https://www.linkedin.com/in/katherine-taylor-858122149/
format:
  html:
    theme: journal
    css: styles.css

editor: visual

