project:
  type: website

website:
  title: "Katherine Taylor"
  navbar:
    right:
      - about.qmd
      - teaching_philosophy.qmd
      - classroom_mgmt.qmd
      - icon: github
        href: https://github.com/katherine-taylor
      - icon: linkedin
        href: https://www.linkedin.com/in/katherine-taylor-858122149/
format:
  html:
    theme: journal
    css: styles.css
page-layout: full
title-block-banner: background.jpg
editor: visual

