---
title: "Classroom Management"
---

My classroom management philosophy is summarized below:

-   Similar to my teaching philosophy, relationships are the center of everything we do

    I have learned firsthand in my placement and experiences working with youth that relationships are what make learning happen. I place a high priority on getting to know students, from learning their names by the third day to attending their sports games and activities. Relationships are truly what do the work of classroom management.

-    Mistakes make learning happen

    For real learning to happen, both in content and socioemotional skills, students will need to feel comfortable making mistakes. From the content perspective, I want students to share their answers and take risks, even if they are wrong. When it comes to behavior and expectations, every student gets a fresh start every day, no matter what happened yesterday. Students are still learning how to exist in our society, and need to be given grace when they make mistakes.

-   Classrooms should represent the community

    As a white, female teacher, I represent the majority of the teaching workforce. I want to teach in diverse schools, where the majority of students do not look like me. With the aid of students, caregivers, and community members, I will iterate on and shape my classroom management system so that it reflects the values of the community. Students will feel more comfortable taking risks academically if they feel comfortable in the classroom.
