---
title: "Teaching Philosophy"
---

My teaching philosophy consists of five key pillars detailed below:

-   Students need to engage in inquiry driven instruction to develop a deep conceptual understanding of math. By engaging in productive struggle, students develop number sense, and a better understanding of math than the rote memorization of procedures.

-   Teaching socioemotional skills is core to deepening students' understanding of math. Without self awareness, management, and relationship skills, students are not prepared to productively struggle with math.

-   Diverse perspectives and experiences are a strength in the classroom. Students should see everyone as doers of mathematics, regardless of race, culture or linguistic background.

-   Our ultimate goal as teachers is to give students transferable skills so they can learn anything they want to. Teaching students skills such as meta cognition enable students to chart a path into life long learning.

-   Relationships are the center of everything we do as teachers. I became a teacher because I want to build relationships as a career. Students need adults in their lives who trust them, believe in them, and want them to succeed.
